AE - Sem's pr
AEnterprise/GearBot pull request #423
Opened 2020-08-29 18:11 UTC by Sem1083

DM_ON_ACTIONS

2020-08-29 18:36 UTC, AEnterprise requested changes
some issues below, also this doesn't actually include the reasons

2020-08-29 18:36 UTC, AEnterprise commented on GearBot/Cogs/Moderation.py
> +        name = Utils.clean_user(user)
why is this here? now regular kick will result in you getting the DM twice, because the line above will cause it to call the _kick function (and you'll even get a DM if they try to kick someone who you can't kick)

2020-08-29 18:36 UTC, AEnterprise commented on GearBot/Cogs/Moderation.py
> +        name = Utils.clean_user(user)
same as above

2020-08-29 18:36 UTC, AEnterprise commented on GearBot/Cogs/Moderation.py
> +                name = Utils.clean_user(user)
again here

2020-08-29 18:36 UTC, AEnterprise commented on lang/en_US.json
> +  "kick_dm": "You have been kicked in **{server}**!",
might be worth changing the wording in these a little bit. like "You have been kicked in _server_ for ..."

2020-08-29 19:20 UTC, Sem1083 commented on GearBot/Cogs/Moderation.py
> +        name = Utils.clean_user(user)
Fixed.

2020-08-29 19:20 UTC, Sem1083 commented on GearBot/Cogs/Moderation.py
> +                name = Utils.clean_user(user)
fixed

2020-08-29 19:20 UTC, Sem1083 commented on lang/en_US.json
> +  "kick_dm": "You have been kicked in **{server}**!",
done

2020-08-30 09:53 UTC, AEnterprise requested changes
tested and still has some issues:

- missing help string for the configuration commands
- unmute does not work (even with DM on unmute disabled, see screenshot)


![image](https://user-images.githubusercontent.com/5206666/91656184-07437e80-eab7-11ea-8a2a-920308f9d498.png)

2020-08-30 11:08 UTC, Sem1083 commented
Seems like I used user instead of target, will fix in a good hour

2020-09-05 08:36 UTC, AEnterprise approved these changes

2020-09-05 08:36 UTC, merged