Subcommand Help change
AEnterprise/GearBot pull request #435
Opened 2021-02-08 20:00 UTC by CaptainStabs

**What does this PR add/fix/improve/...**
Subcommand help page will now print the server's custom prefix.
(Couldn't ever get the bot to connect to my SQL server, so it is currently untested)

Starts the readme file.

2021-02-09 15:50 UTC, AEnterprise requested changes

2021-02-09 15:50 UTC, AEnterprise commented on GearBot/Cogs/ServerAdmin.py
> +            await ctx.send("See the subcommands ({prefix}help configure) for configurations.")
This will not work at all. this will send the literal text 
```
{prefix}help configure) for configurations.
```

what you want to do is make this a format string and substitute the actual prefix from the config instead.

2021-02-13 20:45 UTC, CaptainStabs commented on GearBot/Cogs/ServerAdmin.py
> +            await ctx.send("See the subcommands ({prefix}help configure) for configurations.")
Honestly not sure why I thought this would work :sweat_smile:

2021-02-14 11:45 UTC, AEnterprise commented on GearBot/Cogs/ServerAdmin.py
> +            await ctx.send("See the subcommands ({prefix}help configure) for configurations.")
no the template is what is used to make a config for a new server, you can to use use the configuration helpers to get the config and prefix from the current server

2021-02-16 17:35 UTC, CaptainStabs commented on GearBot/Cogs/ServerAdmin.py
> +            await ctx.send("See the subcommands ({prefix}help configure) for configurations.")
Okay as I'm lost I'll just remove that commit and leave the readme changes

2021-03-13 15:06 UTC, closed without merging